name: Continous integration - E2E

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: E2E tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
